services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_julio
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SenhaForte@123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ../docs/sql/init_julio_db.sql:/var/opt/mssql/scripts/init_julio_db.sql:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -b -C -S localhost -U sa -P \"$${SA_PASSWORD}\" -i /var/opt/mssql/scripts/init_julio_db.sql > /dev/null"
        ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

volumes:
  sqlserver_data:
