spring:
  application:
    name: juliopedidoapi
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=julio_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: SenhaForte@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8080

api:
  viacep:
    url: https://viacep.com.br/
  fipe:
    url: https://fipe.parallelum.com.br/api/v2

juliopedidoapi:
  url: http://localhost:8080

elasticsearch:
  url: http://localhost:9200
  index:
    pedido: pedido

security:
  jwt:
    issuer: JulioApis
    expiration-minutes: 60
    secret: CHAVE_SUPER_SECRETA_JULIO_APIS_COM_NO_MINIMO_32_CARACTERES
